application: a262b48e0907f03384425f09439270
version: 1
runtime: go
api_version: go1

handlers:
- url: /.*
  script: _go_app

- url: /css
  static_dir: stylesheets

- url: /scripts
  static_dir: javascripts
