application: a262b48e0907f03384425f09439270
version: 1
runtime: go
api_version: go1

handlers:
- url: /css
  static_dir: css

- url: /javascripts
  static_dir: javascripts

- url: /.*
  script: _go_app

